# Generated by Django 3.2.4 on 2021-07-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_jobseekerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='user',
            new_name='user_profile',
        ),
    ]
