# Generated by Django 3.2.4 on 2021-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_joboffer_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
