# Generated by Django 3.2.4 on 2021-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210801_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='country',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
