# Generated by Django 3.2.4 on 2021-08-19 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210817_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='interests2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
