# Generated by Django 3.2.4 on 2021-08-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobseekerprofile_interests2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='interests',
        ),
    ]
