# Generated by Django 3.2.4 on 2021-08-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_jobseekerprofile_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='interests2',
            new_name='interests',
        ),
    ]
