# Generated by Django 3.2.4 on 2021-08-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210819_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='languages2',
            new_name='languages',
        ),
    ]
