# Generated by Django 3.2.4 on 2021-08-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_languages2_jobseekerprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_active_jobseeker',
            field=models.BooleanField(default=True),
        ),
    ]
