# Generated by Django 3.2.4 on 2021-09-05 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210823_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='skills2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
