# Generated by Django 3.2.4 on 2021-09-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_joboffer_skills2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='skills',
        ),
    ]
