# Generated by Django 3.2.4 on 2021-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_jobseekerprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='photo',
            field=models.ImageField(blank=True, default='/default_images/jobseeker_default.jpg', upload_to='user_photos/'),
        ),
    ]
