# Generated by Django 3.2.4 on 2021-07-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupationcategory',
            options={'verbose_name_plural': 'Occupation Categories'},
        ),
    ]
