# Generated by Django 3.2.4 on 2021-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
