# Generated by Django 3.2.4 on 2021-07-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('companies', '0003_alter_companyprofile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.occupation'),
        ),
    ]
