# Generated by Django 3.2.4 on 2021-07-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_position_position_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_title',
            new_name='position_occupation',
        ),
    ]
