# Generated by Django 3.2.4 on 2021-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_position_title_position_position_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_info',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
