# Generated by Django 3.2.4 on 2021-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_position_position_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_info',
            field=models.TextField(max_length=20000),
        ),
    ]
