# Generated by Django 3.2.4 on 2021-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_occupationcategory_options'),
        ('companies', '0007_alter_position_position_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.occupation'),
        ),
    ]
