# Generated by Django 3.2.4 on 2021-08-19 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20210817_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_languages2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
