# Generated by Django 3.2.4 on 2021-08-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_position_position_languages2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_languages',
        ),
    ]
