# Generated by Django 3.2.4 on 2021-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20210826_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='background_photo',
            field=models.ImageField(blank=True, default='/default_images/jobseeker_default_background.jpg', upload_to='company_photos/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, default='/default_images/company_default.jpg', upload_to='company_photos/'),
        ),
    ]
