# Generated by Django 3.2.4 on 2021-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20210914_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
