# Generated by Django 3.2.4 on 2021-09-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usermodel_has_premium'),
        ('companies', '0018_auto_20210922_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='position',
            name='denied',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobseeker_accepted', models.BooleanField(null=True)),
                ('company_accepted', models.BooleanField(null=True)),
                ('matched', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseekerprofile')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.position')),
            ],
        ),
    ]
