# Generated by Django 3.2.4 on 2021-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_alter_match_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, max_length=200),
        ),
    ]
